Feat/video controller
supurazako/makiMakiStream pull request #4
Opened 2024-12-13 12:42 UTC by Zemelua

2024-12-15 08:28 UTC, supurazako requested changes

2024-12-15 08:28 UTC, supurazako commented on app/components/video_controllers.css
EOFに改行

2024-12-15 08:28 UTC, supurazako commented on app/routes/dev.video_controllers.tsx
EOFに改行

2024-12-16 08:19 UTC, Zemelua commented on app/components/video_controllers.css
修正

2024-12-16 08:19 UTC, Zemelua commented on app/routes/dev.video_controllers.tsx
修正

2025-01-11 08:29 UTC, supurazako approved these changes
カーソルがホバーしていないとき、
volume_sliderが0の場合は問題ないが、1のときは埋まってしまうという問題がある。
![image](https://github.com/user-attachments/assets/7a9db799-6d39-46cf-ba00-8012c00221c7)

2025-01-11 13:39 UTC, merged